#!/bin/python3
from scripts import *
import pandas as pd

def match_spectrum(wtlist, peaks, tolerance=20):
    #TODO
    # matches a weight list as generated by fragmass with a list of peaks identified by call_peaks
    pass

def call_peaks(spectrum):
    #TODO
    # identifies peaks in a spectrum, input as a pandas DF containing m/z and intensity information
    pass


def get_tryptic_peptide(aaseq: str, spectrum: pd.DataFrame):
    # returns the tryptic peptide of the protein specified by aaseq best fitting the spectrum, supplied as a pandas DF
    tryptics = trypticdigest(aaseq, minwt=0)
    peaks = call_peaks(spectrum)

    maxp = 0
    maxtr = None
    for tr in tryptics:
        p = match_spectrum(fragmass(tr), peaks)
        if p > maxp:
            maxp = p
            maxtr = tr

    return maxp, maxtr

if __name__ == '__main__':
    df = pd.read_csv('./exspec.csv')

