---
title: "Exercise05_noncodingRNA"
author: "Maximilian Harl, Leon Hafner, Leon Rauschning, David Wagemann"
date: "21.6.2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Exercise 05 - noncoding RNA

This is where the exercise starts. You can also delete the chunks above in your final version.

```{r}
# some setups
set.seed(123)

# load libraries
library(SPONGE)
library(data.table)
library(doParallel)
library(foreach)
library(dplyr)

# parallelization
num.of.cores <- 8
cl <- makeCluster(num.of.cores) 
registerDoParallel(cl)
```

## a) Data acquisition and preparation 

```{r}
load("oldCohort.RData")
genexp <- tgct_oldCohort_gene_expression
meta <- tgct_oldCohort_metaData
mirna <- tgct_oldCohort_miRNA_expression
#TODO test/train split
```

## b) Sponge modules 

```{r}
ceRNA_interactions <- data.table::fread('testicular_germ_cell_tumor/testicular_germ_cell_tumor_networkInteractions_full.csv') 
network_centralities <- data.table::fread('testicular_germ_cell_tumor/testicular_germ_cell_tumor_networkAnalysis.csv')

colnames(ceRNA_interactions)[which(colnames(ceRNA_interactions) == 'GeneA')] <- 'geneA'
colnames(ceRNA_interactions)[which(colnames(ceRNA_interactions) == 'GeneB')] <- 'geneB'

# untested
filtered_network_centralities <- filter_ceRNA_network(
	sponge_effects = ceRNA_interactions,
	Node_Centrality = network_centralities,
	add_weighted_centrality=T,
	mscor.threshold = 0.01,
	padj.threshold = 0.1)

```

## c) Module enrichment + Machine learning

```{r}
#insert code here
```

```{r}
print(paste0('Sensitivity: ',0))
print(paste0('Specificity: ',0))
print(paste0('Balanced Accuracy: ',0))
```
## d) Visualisation and Interpretation

```{r}
#insert code here
```

```{r}
#next plot
```
I can interpret this plot!

```{r}
#one more plot?
```
this is more difficult..

```{r}
#wow, another one! 
```
I really want these bonus points!

```{r}
#this is getting out of hand...
```

```{r}
#stop your backend parallelisation if registered
stopCluster(cl) 
```
